---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.yum:
      update_cache: true

  - name: install httpd package
    ansible.builtin.yum:
      name: httpd
      state: latest

  - name: install support for php
    ansible.builtin.yum:
      name: php
      state: latest
