---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.yum:
      update_cache: true

  - name: remove httpd package
    ansible.builtin.yum:
      name: httpd
      state: absent
